name: .NET Build and Test

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x # Updated to use .NET 6.0

    - name: Build and Test
      id: build-and-test
      run: |
        dotnet build
        dotnet test --logger "trx;LogFileName=test_results.xml"

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      with:
        files: '**/test_results.xml'
        format: VSTest
